DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS reminders;

CREATE TABLE messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userid TEXT UNIQUE NOT NULL,
  message TEXT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reminders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  userid TEXT UNIQUE NOT NULL,
  deadline TIMESTAMP
)
